namespace CampusConnect.Forms
{
    partial class Add_Internships
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            this.lblPageTitle = new System.Windows.Forms.Label();
            this.btnExit = new System.Windows.Forms.Button();
            this.panelCard = new System.Windows.Forms.Panel();
            this.btnAdd = new System.Windows.Forms.Button();
            this.lblCompany = new System.Windows.Forms.Label();
            this.txtCompany = new System.Windows.Forms.TextBox();
            this.lblJobRole = new System.Windows.Forms.Label();
            this.txtJobRole = new System.Windows.Forms.TextBox();
            this.lblDescription = new System.Windows.Forms.Label();
            this.txtDescription = new System.Windows.Forms.TextBox();
            this.lblStartYear = new System.Windows.Forms.Label();
            this.txtStartYear = new System.Windows.Forms.TextBox();
            this.lblEndDate = new System.Windows.Forms.Label();
            this.txtEndDate = new System.Windows.Forms.TextBox();
            this.panelCard.SuspendLayout();
            this.SuspendLayout();
            this.lblPageTitle.AutoSize = true;
            this.lblPageTitle.Font = new System.Drawing.Font("Montserrat", 20F, System.Drawing.FontStyle.Bold);
            this.lblPageTitle.ForeColor = System.Drawing.Color.White;
            this.lblPageTitle.Location = new System.Drawing.Point(40, 36);
            this.lblPageTitle.Name = "lblPageTitle";
            this.lblPageTitle.TabIndex = 0;
            this.lblPageTitle.Text = "Add Internship";
            this.btnExit.BackColor = System.Drawing.Color.Red;
            this.btnExit.FlatAppearance.BorderSize = 0;
            this.btnExit.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnExit.Font = new System.Drawing.Font("Montserrat Medium", 10F, System.Drawing.FontStyle.Bold);
            this.btnExit.ForeColor = System.Drawing.Color.White;
            this.btnExit.Location = new System.Drawing.Point(40, 596);
            this.btnExit.Name = "btnExit";
            this.btnExit.Size = new System.Drawing.Size(110, 38);
            this.btnExit.TabIndex = 1;
            this.btnExit.Text = "Go Back";
            this.btnExit.UseVisualStyleBackColor = false;
            this.btnExit.Click += new System.EventHandler(this.btnExit_Click);
            this.panelCard.BackColor = System.Drawing.Color.FromArgb(68, 72, 71);
            this.panelCard.Controls.Add(this.btnAdd);
            this.panelCard.Controls.Add(this.txtCompany);
            this.panelCard.Controls.Add(this.txtJobRole);
            this.panelCard.Controls.Add(this.txtDescription);
            this.panelCard.Controls.Add(this.txtStartYear);
            this.panelCard.Controls.Add(this.txtEndDate);
            this.panelCard.Controls.Add(this.lblCompany);
            this.panelCard.Controls.Add(this.lblJobRole);
            this.panelCard.Controls.Add(this.lblDescription);
            this.panelCard.Controls.Add(this.lblStartYear);
            this.panelCard.Controls.Add(this.lblEndDate);
            this.panelCard.Location = new System.Drawing.Point(300, 60);
            this.panelCard.Name = "panelCard";
            this.panelCard.Size = new System.Drawing.Size(580, 590);
            this.panelCard.TabIndex = 2;
            this.lblCompany.AutoSize = true;
            this.lblCompany.Font = new System.Drawing.Font("Montserrat Medium", 10F, System.Drawing.FontStyle.Bold);
            this.lblCompany.ForeColor = System.Drawing.Color.White;
            this.lblCompany.Location = new System.Drawing.Point(30, 90);
            this.lblCompany.Name = "lblCompany";
            this.lblCompany.TabIndex = 0;
            this.lblCompany.Text = "Company Name";
            this.txtCompany.BackColor = System.Drawing.Color.FromArgb(44, 49, 49);
            this.txtCompany.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtCompany.Font = new System.Drawing.Font("Montserrat", 10F);
            this.txtCompany.ForeColor = System.Drawing.Color.White;
            this.txtCompany.Location = new System.Drawing.Point(30, 116);
            this.txtCompany.Name = "txtCompany";
            this.txtCompany.Size = new System.Drawing.Size(500, 32);
            this.txtCompany.TabIndex = 1;
            this.lblJobRole.AutoSize = true;
            this.lblJobRole.Font = new System.Drawing.Font("Montserrat Medium", 10F, System.Drawing.FontStyle.Bold);
            this.lblJobRole.ForeColor = System.Drawing.Color.White;
            this.lblJobRole.Location = new System.Drawing.Point(30, 170);
            this.lblJobRole.Name = "lblJobRole";
            this.lblJobRole.TabIndex = 2;
            this.lblJobRole.Text = "Job Role";
            this.txtJobRole.BackColor = System.Drawing.Color.FromArgb(44, 49, 49);
            this.txtJobRole.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtJobRole.Font = new System.Drawing.Font("Montserrat", 10F);
            this.txtJobRole.ForeColor = System.Drawing.Color.White;
            this.txtJobRole.Location = new System.Drawing.Point(30, 196);
            this.txtJobRole.Name = "txtJobRole";
            this.txtJobRole.Size = new System.Drawing.Size(500, 32);
            this.txtJobRole.TabIndex = 3;
            this.lblDescription.AutoSize = true;
            this.lblDescription.Font = new System.Drawing.Font("Montserrat Medium", 10F, System.Drawing.FontStyle.Bold);
            this.lblDescription.ForeColor = System.Drawing.Color.White;
            this.lblDescription.Location = new System.Drawing.Point(30, 250);
            this.lblDescription.Name = "lblDescription";
            this.lblDescription.TabIndex = 4;
            this.lblDescription.Text = "Description";
            this.txtDescription.BackColor = System.Drawing.Color.FromArgb(44, 49, 49);
            this.txtDescription.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtDescription.Font = new System.Drawing.Font("Montserrat", 10F);
            this.txtDescription.ForeColor = System.Drawing.Color.White;
            this.txtDescription.Location = new System.Drawing.Point(30, 276);
            this.txtDescription.Multiline = true;
            this.txtDescription.Name = "txtDescription";
            this.txtDescription.Size = new System.Drawing.Size(500, 70);
            this.txtDescription.TabIndex = 5;
            this.lblStartYear.AutoSize = true;
            this.lblStartYear.Font = new System.Drawing.Font("Montserrat Medium", 10F, System.Drawing.FontStyle.Bold);
            this.lblStartYear.ForeColor = System.Drawing.Color.White;
            this.lblStartYear.Location = new System.Drawing.Point(30, 330);
            this.lblStartYear.Name = "lblStartYear";
            this.lblStartYear.TabIndex = 6;
            this.lblStartYear.Text = "Start Year";
            this.txtStartYear.BackColor = System.Drawing.Color.FromArgb(44, 49, 49);
            this.txtStartYear.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtStartYear.Font = new System.Drawing.Font("Montserrat", 10F);
            this.txtStartYear.ForeColor = System.Drawing.Color.White;
            this.txtStartYear.Location = new System.Drawing.Point(30, 356);
            this.txtStartYear.Name = "txtStartYear";
            this.txtStartYear.Size = new System.Drawing.Size(500, 32);
            this.txtStartYear.TabIndex = 7;
            this.lblEndDate.AutoSize = true;
            this.lblEndDate.Font = new System.Drawing.Font("Montserrat Medium", 10F, System.Drawing.FontStyle.Bold);
            this.lblEndDate.ForeColor = System.Drawing.Color.White;
            this.lblEndDate.Location = new System.Drawing.Point(30, 410);
            this.lblEndDate.Name = "lblEndDate";
            this.lblEndDate.TabIndex = 8;
            this.lblEndDate.Text = "End Date";
            this.txtEndDate.BackColor = System.Drawing.Color.FromArgb(44, 49, 49);
            this.txtEndDate.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtEndDate.Font = new System.Drawing.Font("Montserrat", 10F);
            this.txtEndDate.ForeColor = System.Drawing.Color.White;
            this.txtEndDate.Location = new System.Drawing.Point(30, 436);
            this.txtEndDate.Name = "txtEndDate";
            this.txtEndDate.Size = new System.Drawing.Size(500, 32);
            this.txtEndDate.TabIndex = 9;
            this.btnAdd.BackColor = System.Drawing.Color.FromArgb(52, 193, 164);
            this.btnAdd.FlatAppearance.BorderSize = 0;
            this.btnAdd.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAdd.Font = new System.Drawing.Font("Montserrat Medium", 12F, System.Drawing.FontStyle.Bold);
            this.btnAdd.ForeColor = System.Drawing.Color.White;
            this.btnAdd.Location = new System.Drawing.Point(30, 510);
            this.btnAdd.Name = "btnAdd";
            this.btnAdd.Size = new System.Drawing.Size(140, 44);
            this.btnAdd.TabIndex = 99;
            this.btnAdd.Text = "Add";
            this.btnAdd.UseVisualStyleBackColor = false;
            this.btnAdd.Click += new System.EventHandler(this.btnAdd_Click);
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(44, 49, 49);
            this.ClientSize = new System.Drawing.Size(1180, 656);
            this.Controls.Add(this.lblPageTitle);
            this.Controls.Add(this.btnExit);
            this.Controls.Add(this.panelCard);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MaximizeBox = false;
            this.Name = "Add_Internships";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Add Internship";
            this.panelCard.ResumeLayout(false);
            this.panelCard.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        #endregion
        private System.Windows.Forms.Label lblPageTitle;
        private System.Windows.Forms.Button btnExit;
        private System.Windows.Forms.Panel panelCard;
        private System.Windows.Forms.Button btnAdd;
        private System.Windows.Forms.Label lblCompany;
        private System.Windows.Forms.TextBox txtCompany;
        private System.Windows.Forms.Label lblJobRole;
        private System.Windows.Forms.TextBox txtJobRole;
        private System.Windows.Forms.Label lblDescription;
        private System.Windows.Forms.TextBox txtDescription;
        private System.Windows.Forms.Label lblStartYear;
        private System.Windows.Forms.TextBox txtStartYear;
        private System.Windows.Forms.Label lblEndDate;
        private System.Windows.Forms.TextBox txtEndDate;
    }
}
