namespace CampusConnect.Forms
{
    partial class Add_Education
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            this.lblPageTitle = new System.Windows.Forms.Label();
            this.btnExit = new System.Windows.Forms.Button();
            this.panelCard = new System.Windows.Forms.Panel();
            this.btnAdd = new System.Windows.Forms.Button();
            this.lblInstitute = new System.Windows.Forms.Label();
            this.txtInstitute = new System.Windows.Forms.TextBox();
            this.lblDegree = new System.Windows.Forms.Label();
            this.txtDegree = new System.Windows.Forms.TextBox();
            this.lblStartYear = new System.Windows.Forms.Label();
            this.txtStartYear = new System.Windows.Forms.TextBox();
            this.lblEndYear = new System.Windows.Forms.Label();
            this.txtEndYear = new System.Windows.Forms.TextBox();
            this.panelCard.SuspendLayout();
            this.SuspendLayout();
            this.lblPageTitle.AutoSize = true;
            this.lblPageTitle.Font = new System.Drawing.Font("Montserrat", 20F, System.Drawing.FontStyle.Bold);
            this.lblPageTitle.ForeColor = System.Drawing.Color.White;
            this.lblPageTitle.Location = new System.Drawing.Point(40, 36);
            this.lblPageTitle.Name = "lblPageTitle";
            this.lblPageTitle.TabIndex = 0;
            this.lblPageTitle.Text = "Add Education";
            this.btnExit.BackColor = System.Drawing.Color.Red;
            this.btnExit.FlatAppearance.BorderSize = 0;
            this.btnExit.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnExit.Font = new System.Drawing.Font("Montserrat Medium", 10F, System.Drawing.FontStyle.Bold);
            this.btnExit.ForeColor = System.Drawing.Color.White;
            this.btnExit.Location = new System.Drawing.Point(40, 596);
            this.btnExit.Name = "btnExit";
            this.btnExit.Size = new System.Drawing.Size(110, 38);
            this.btnExit.TabIndex = 1;
            this.btnExit.Text = "Go Back";
            this.btnExit.UseVisualStyleBackColor = false;
            this.btnExit.Click += new System.EventHandler(this.btnExit_Click);
            this.panelCard.BackColor = System.Drawing.Color.FromArgb(68, 72, 71);
            this.panelCard.Controls.Add(this.btnAdd);
            this.panelCard.Controls.Add(this.txtInstitute);
            this.panelCard.Controls.Add(this.txtDegree);
            this.panelCard.Controls.Add(this.txtStartYear);
            this.panelCard.Controls.Add(this.txtEndYear);
            this.panelCard.Controls.Add(this.lblInstitute);
            this.panelCard.Controls.Add(this.lblDegree);
            this.panelCard.Controls.Add(this.lblStartYear);
            this.panelCard.Controls.Add(this.lblEndYear);
            this.panelCard.Location = new System.Drawing.Point(300, 73);
            this.panelCard.Name = "panelCard";
            this.panelCard.Size = new System.Drawing.Size(580, 510);
            this.panelCard.TabIndex = 2;
            this.lblInstitute.AutoSize = true;
            this.lblInstitute.Font = new System.Drawing.Font("Montserrat Medium", 10F, System.Drawing.FontStyle.Bold);
            this.lblInstitute.ForeColor = System.Drawing.Color.White;
            this.lblInstitute.Location = new System.Drawing.Point(30, 90);
            this.lblInstitute.Name = "lblInstitute";
            this.lblInstitute.TabIndex = 0;
            this.lblInstitute.Text = "Institute Name";
            this.txtInstitute.BackColor = System.Drawing.Color.FromArgb(44, 49, 49);
            this.txtInstitute.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtInstitute.Font = new System.Drawing.Font("Montserrat", 10F);
            this.txtInstitute.ForeColor = System.Drawing.Color.White;
            this.txtInstitute.Location = new System.Drawing.Point(30, 116);
            this.txtInstitute.Name = "txtInstitute";
            this.txtInstitute.Size = new System.Drawing.Size(500, 32);
            this.txtInstitute.TabIndex = 1;
            this.lblDegree.AutoSize = true;
            this.lblDegree.Font = new System.Drawing.Font("Montserrat Medium", 10F, System.Drawing.FontStyle.Bold);
            this.lblDegree.ForeColor = System.Drawing.Color.White;
            this.lblDegree.Location = new System.Drawing.Point(30, 170);
            this.lblDegree.Name = "lblDegree";
            this.lblDegree.TabIndex = 2;
            this.lblDegree.Text = "Degree";
            this.txtDegree.BackColor = System.Drawing.Color.FromArgb(44, 49, 49);
            this.txtDegree.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtDegree.Font = new System.Drawing.Font("Montserrat", 10F);
            this.txtDegree.ForeColor = System.Drawing.Color.White;
            this.txtDegree.Location = new System.Drawing.Point(30, 196);
            this.txtDegree.Name = "txtDegree";
            this.txtDegree.Size = new System.Drawing.Size(500, 32);
            this.txtDegree.TabIndex = 3;
            this.lblStartYear.AutoSize = true;
            this.lblStartYear.Font = new System.Drawing.Font("Montserrat Medium", 10F, System.Drawing.FontStyle.Bold);
            this.lblStartYear.ForeColor = System.Drawing.Color.White;
            this.lblStartYear.Location = new System.Drawing.Point(30, 250);
            this.lblStartYear.Name = "lblStartYear";
            this.lblStartYear.TabIndex = 4;
            this.lblStartYear.Text = "Start Year";
            this.txtStartYear.BackColor = System.Drawing.Color.FromArgb(44, 49, 49);
            this.txtStartYear.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtStartYear.Font = new System.Drawing.Font("Montserrat", 10F);
            this.txtStartYear.ForeColor = System.Drawing.Color.White;
            this.txtStartYear.Location = new System.Drawing.Point(30, 276);
            this.txtStartYear.Name = "txtStartYear";
            this.txtStartYear.Size = new System.Drawing.Size(500, 32);
            this.txtStartYear.TabIndex = 5;
            this.lblEndYear.AutoSize = true;
            this.lblEndYear.Font = new System.Drawing.Font("Montserrat Medium", 10F, System.Drawing.FontStyle.Bold);
            this.lblEndYear.ForeColor = System.Drawing.Color.White;
            this.lblEndYear.Location = new System.Drawing.Point(30, 330);
            this.lblEndYear.Name = "lblEndYear";
            this.lblEndYear.TabIndex = 6;
            this.lblEndYear.Text = "End Year";
            this.txtEndYear.BackColor = System.Drawing.Color.FromArgb(44, 49, 49);
            this.txtEndYear.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtEndYear.Font = new System.Drawing.Font("Montserrat", 10F);
            this.txtEndYear.ForeColor = System.Drawing.Color.White;
            this.txtEndYear.Location = new System.Drawing.Point(30, 356);
            this.txtEndYear.Name = "txtEndYear";
            this.txtEndYear.Size = new System.Drawing.Size(500, 32);
            this.txtEndYear.TabIndex = 7;
            this.btnAdd.BackColor = System.Drawing.Color.FromArgb(52, 193, 164);
            this.btnAdd.FlatAppearance.BorderSize = 0;
            this.btnAdd.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAdd.Font = new System.Drawing.Font("Montserrat Medium", 12F, System.Drawing.FontStyle.Bold);
            this.btnAdd.ForeColor = System.Drawing.Color.White;
            this.btnAdd.Location = new System.Drawing.Point(30, 430);
            this.btnAdd.Name = "btnAdd";
            this.btnAdd.Size = new System.Drawing.Size(140, 44);
            this.btnAdd.TabIndex = 99;
            this.btnAdd.Text = "Add";
            this.btnAdd.UseVisualStyleBackColor = false;
            this.btnAdd.Click += new System.EventHandler(this.btnAdd_Click);
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(44, 49, 49);
            this.ClientSize = new System.Drawing.Size(1180, 656);
            this.Controls.Add(this.lblPageTitle);
            this.Controls.Add(this.btnExit);
            this.Controls.Add(this.panelCard);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MaximizeBox = false;
            this.Name = "Add_Education";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Add Education";
            this.panelCard.ResumeLayout(false);
            this.panelCard.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        #endregion
        private System.Windows.Forms.Label lblPageTitle;
        private System.Windows.Forms.Button btnExit;
        private System.Windows.Forms.Panel panelCard;
        private System.Windows.Forms.Button btnAdd;
        private System.Windows.Forms.Label lblInstitute;
        private System.Windows.Forms.TextBox txtInstitute;
        private System.Windows.Forms.Label lblDegree;
        private System.Windows.Forms.TextBox txtDegree;
        private System.Windows.Forms.Label lblStartYear;
        private System.Windows.Forms.TextBox txtStartYear;
        private System.Windows.Forms.Label lblEndYear;
        private System.Windows.Forms.TextBox txtEndYear;
    }
}
