namespace CampusConnect.Forms
{
    partial class Admin_Reports
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            this.panelSidebar = new System.Windows.Forms.Panel();
            this.lblSideTitle = new System.Windows.Forms.Label();
            this.btnExit = new System.Windows.Forms.Button();
            this.lblPageTitle = new System.Windows.Forms.Label();
            this.panelReport1 = new System.Windows.Forms.Panel();
            this.lblReport1 = new System.Windows.Forms.Label();
            this.btnReport1 = new System.Windows.Forms.Button();
            this.panelReport2 = new System.Windows.Forms.Panel();
            this.lblReport2 = new System.Windows.Forms.Label();
            this.btnReport2 = new System.Windows.Forms.Button();
            this.panelReport3 = new System.Windows.Forms.Panel();
            this.lblReport3 = new System.Windows.Forms.Label();
            this.btnReport3 = new System.Windows.Forms.Button();
            this.panelReport4 = new System.Windows.Forms.Panel();
            this.lblReport4 = new System.Windows.Forms.Label();
            this.btnReport4 = new System.Windows.Forms.Button();
            this.panelReport5 = new System.Windows.Forms.Panel();
            this.lblReport5 = new System.Windows.Forms.Label();
            this.btnReport5 = new System.Windows.Forms.Button();
            this.panelReport6 = new System.Windows.Forms.Panel();
            this.lblReport6 = new System.Windows.Forms.Label();
            this.btnReport6 = new System.Windows.Forms.Button();
            this.panelReport7 = new System.Windows.Forms.Panel();
            this.lblReport7 = new System.Windows.Forms.Label();
            this.btnReport7 = new System.Windows.Forms.Button();
            this.panelReport8 = new System.Windows.Forms.Panel();
            this.lblReport8 = new System.Windows.Forms.Label();
            this.btnReport8 = new System.Windows.Forms.Button();
            this.panelReport9 = new System.Windows.Forms.Panel();
            this.lblReport9 = new System.Windows.Forms.Label();
            this.btnReport9 = new System.Windows.Forms.Button();
            this.panelReport10 = new System.Windows.Forms.Panel();
            this.lblReport10 = new System.Windows.Forms.Label();
            this.btnReport10 = new System.Windows.Forms.Button();
            this.panelSidebar.SuspendLayout();
            this.panelReport1.SuspendLayout();
            this.panelReport2.SuspendLayout();
            this.panelReport3.SuspendLayout();
            this.panelReport4.SuspendLayout();
            this.panelReport5.SuspendLayout();
            this.panelReport6.SuspendLayout();
            this.panelReport7.SuspendLayout();
            this.panelReport8.SuspendLayout();
            this.panelReport9.SuspendLayout();
            this.panelReport10.SuspendLayout();
            this.SuspendLayout();
            this.panelSidebar.BackColor = System.Drawing.Color.FromArgb(68, 72, 71);
            this.panelSidebar.Controls.Add(this.lblSideTitle);
            this.panelSidebar.Controls.Add(this.btnExit);
            this.panelSidebar.Dock = System.Windows.Forms.DockStyle.Left;
            this.panelSidebar.Name = "panelSidebar";
            this.panelSidebar.Size = new System.Drawing.Size(280, 656);
            this.panelSidebar.TabIndex = 0;
            this.lblSideTitle.Font = new System.Drawing.Font("Montserrat", 20F, System.Drawing.FontStyle.Bold);
            this.lblSideTitle.ForeColor = System.Drawing.Color.White;
            this.lblSideTitle.Location = new System.Drawing.Point(20, 260);
            this.lblSideTitle.Name = "lblSideTitle";
            this.lblSideTitle.Size = new System.Drawing.Size(240, 80);
            this.lblSideTitle.TabIndex = 0;
            this.lblSideTitle.Text = "Reports";
            this.btnExit.BackColor = System.Drawing.Color.Red;
            this.btnExit.FlatAppearance.BorderSize = 0;
            this.btnExit.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnExit.Font = new System.Drawing.Font("Montserrat Medium", 11F, System.Drawing.FontStyle.Bold);
            this.btnExit.ForeColor = System.Drawing.Color.White;
            this.btnExit.Location = new System.Drawing.Point(20, 600);
            this.btnExit.Name = "btnExit";
            this.btnExit.Size = new System.Drawing.Size(110, 38);
            this.btnExit.TabIndex = 1;
            this.btnExit.Text = "Go Back";
            this.btnExit.UseVisualStyleBackColor = false;
            this.btnExit.Click += new System.EventHandler(this.btnExit_Click);
            this.lblPageTitle.AutoSize = true;
            this.lblPageTitle.Font = new System.Drawing.Font("Montserrat", 20F, System.Drawing.FontStyle.Bold);
            this.lblPageTitle.ForeColor = System.Drawing.Color.White;
            this.lblPageTitle.Location = new System.Drawing.Point(320, 40);
            this.lblPageTitle.Name = "lblPageTitle";
            this.lblPageTitle.TabIndex = 1;
            this.lblPageTitle.Text = "Platform Reports";
            this.panelReport1.BackColor = System.Drawing.Color.FromArgb(68, 72, 71);
            this.panelReport1.Controls.Add(this.lblReport1);
            this.panelReport1.Controls.Add(this.btnReport1);
            this.panelReport1.Location = new System.Drawing.Point(320, 90);
            this.panelReport1.Name = "panelReport1";
            this.panelReport1.Size = new System.Drawing.Size(166, 210);
            this.panelReport1.TabIndex = 2;
            this.lblReport1.Font = new System.Drawing.Font("Montserrat Medium", 9F, System.Drawing.FontStyle.Bold);
            this.lblReport1.ForeColor = System.Drawing.Color.White;
            this.lblReport1.Location = new System.Drawing.Point(12, 14);
            this.lblReport1.Name = "lblReport1";
            this.lblReport1.Size = new System.Drawing.Size(142, 120);
            this.lblReport1.TabIndex = 0;
            this.lblReport1.Text = "Report 1\r\nDummy report data for section 1. Total records: 42. Status: Active.";
            this.btnReport1.BackColor = System.Drawing.Color.FromArgb(52, 193, 164);
            this.btnReport1.FlatAppearance.BorderSize = 0;
            this.btnReport1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnReport1.Font = new System.Drawing.Font("Montserrat Medium", 9F, System.Drawing.FontStyle.Bold);
            this.btnReport1.ForeColor = System.Drawing.Color.White;
            this.btnReport1.Location = new System.Drawing.Point(12, 160);
            this.btnReport1.Name = "btnReport1";
            this.btnReport1.Size = new System.Drawing.Size(100, 32);
            this.btnReport1.TabIndex = 1;
            this.btnReport1.Text = "View";
            this.btnReport1.UseVisualStyleBackColor = false;
            this.panelReport2.BackColor = System.Drawing.Color.FromArgb(68, 72, 71);
            this.panelReport2.Controls.Add(this.lblReport2);
            this.panelReport2.Controls.Add(this.btnReport2);
            this.panelReport2.Location = new System.Drawing.Point(498, 90);
            this.panelReport2.Name = "panelReport2";
            this.panelReport2.Size = new System.Drawing.Size(166, 210);
            this.panelReport2.TabIndex = 3;
            this.lblReport2.Font = new System.Drawing.Font("Montserrat Medium", 9F, System.Drawing.FontStyle.Bold);
            this.lblReport2.ForeColor = System.Drawing.Color.White;
            this.lblReport2.Location = new System.Drawing.Point(12, 14);
            this.lblReport2.Name = "lblReport2";
            this.lblReport2.Size = new System.Drawing.Size(142, 120);
            this.lblReport2.TabIndex = 0;
            this.lblReport2.Text = "Report 2\r\nDummy report data for section 2. Total records: 84. Status: Active.";
            this.btnReport2.BackColor = System.Drawing.Color.FromArgb(52, 193, 164);
            this.btnReport2.FlatAppearance.BorderSize = 0;
            this.btnReport2.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnReport2.Font = new System.Drawing.Font("Montserrat Medium", 9F, System.Drawing.FontStyle.Bold);
            this.btnReport2.ForeColor = System.Drawing.Color.White;
            this.btnReport2.Location = new System.Drawing.Point(12, 160);
            this.btnReport2.Name = "btnReport2";
            this.btnReport2.Size = new System.Drawing.Size(100, 32);
            this.btnReport2.TabIndex = 1;
            this.btnReport2.Text = "View";
            this.btnReport2.UseVisualStyleBackColor = false;
            this.panelReport3.BackColor = System.Drawing.Color.FromArgb(68, 72, 71);
            this.panelReport3.Controls.Add(this.lblReport3);
            this.panelReport3.Controls.Add(this.btnReport3);
            this.panelReport3.Location = new System.Drawing.Point(676, 90);
            this.panelReport3.Name = "panelReport3";
            this.panelReport3.Size = new System.Drawing.Size(166, 210);
            this.panelReport3.TabIndex = 4;
            this.lblReport3.Font = new System.Drawing.Font("Montserrat Medium", 9F, System.Drawing.FontStyle.Bold);
            this.lblReport3.ForeColor = System.Drawing.Color.White;
            this.lblReport3.Location = new System.Drawing.Point(12, 14);
            this.lblReport3.Name = "lblReport3";
            this.lblReport3.Size = new System.Drawing.Size(142, 120);
            this.lblReport3.TabIndex = 0;
            this.lblReport3.Text = "Report 3\r\nDummy report data for section 3. Total records: 126. Status: Active.";
            this.btnReport3.BackColor = System.Drawing.Color.FromArgb(52, 193, 164);
            this.btnReport3.FlatAppearance.BorderSize = 0;
            this.btnReport3.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnReport3.Font = new System.Drawing.Font("Montserrat Medium", 9F, System.Drawing.FontStyle.Bold);
            this.btnReport3.ForeColor = System.Drawing.Color.White;
            this.btnReport3.Location = new System.Drawing.Point(12, 160);
            this.btnReport3.Name = "btnReport3";
            this.btnReport3.Size = new System.Drawing.Size(100, 32);
            this.btnReport3.TabIndex = 1;
            this.btnReport3.Text = "View";
            this.btnReport3.UseVisualStyleBackColor = false;
            this.panelReport4.BackColor = System.Drawing.Color.FromArgb(68, 72, 71);
            this.panelReport4.Controls.Add(this.lblReport4);
            this.panelReport4.Controls.Add(this.btnReport4);
            this.panelReport4.Location = new System.Drawing.Point(854, 90);
            this.panelReport4.Name = "panelReport4";
            this.panelReport4.Size = new System.Drawing.Size(166, 210);
            this.panelReport4.TabIndex = 5;
            this.lblReport4.Font = new System.Drawing.Font("Montserrat Medium", 9F, System.Drawing.FontStyle.Bold);
            this.lblReport4.ForeColor = System.Drawing.Color.White;
            this.lblReport4.Location = new System.Drawing.Point(12, 14);
            this.lblReport4.Name = "lblReport4";
            this.lblReport4.Size = new System.Drawing.Size(142, 120);
            this.lblReport4.TabIndex = 0;
            this.lblReport4.Text = "Report 4\r\nDummy report data for section 4. Total records: 168. Status: Active.";
            this.btnReport4.BackColor = System.Drawing.Color.FromArgb(52, 193, 164);
            this.btnReport4.FlatAppearance.BorderSize = 0;
            this.btnReport4.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnReport4.Font = new System.Drawing.Font("Montserrat Medium", 9F, System.Drawing.FontStyle.Bold);
            this.btnReport4.ForeColor = System.Drawing.Color.White;
            this.btnReport4.Location = new System.Drawing.Point(12, 160);
            this.btnReport4.Name = "btnReport4";
            this.btnReport4.Size = new System.Drawing.Size(100, 32);
            this.btnReport4.TabIndex = 1;
            this.btnReport4.Text = "View";
            this.btnReport4.UseVisualStyleBackColor = false;
            this.panelReport5.BackColor = System.Drawing.Color.FromArgb(68, 72, 71);
            this.panelReport5.Controls.Add(this.lblReport5);
            this.panelReport5.Controls.Add(this.btnReport5);
            this.panelReport5.Location = new System.Drawing.Point(1032, 90);
            this.panelReport5.Name = "panelReport5";
            this.panelReport5.Size = new System.Drawing.Size(166, 210);
            this.panelReport5.TabIndex = 6;
            this.lblReport5.Font = new System.Drawing.Font("Montserrat Medium", 9F, System.Drawing.FontStyle.Bold);
            this.lblReport5.ForeColor = System.Drawing.Color.White;
            this.lblReport5.Location = new System.Drawing.Point(12, 14);
            this.lblReport5.Name = "lblReport5";
            this.lblReport5.Size = new System.Drawing.Size(142, 120);
            this.lblReport5.TabIndex = 0;
            this.lblReport5.Text = "Report 5\r\nDummy report data for section 5. Total records: 210. Status: Active.";
            this.btnReport5.BackColor = System.Drawing.Color.FromArgb(52, 193, 164);
            this.btnReport5.FlatAppearance.BorderSize = 0;
            this.btnReport5.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnReport5.Font = new System.Drawing.Font("Montserrat Medium", 9F, System.Drawing.FontStyle.Bold);
            this.btnReport5.ForeColor = System.Drawing.Color.White;
            this.btnReport5.Location = new System.Drawing.Point(12, 160);
            this.btnReport5.Name = "btnReport5";
            this.btnReport5.Size = new System.Drawing.Size(100, 32);
            this.btnReport5.TabIndex = 1;
            this.btnReport5.Text = "View";
            this.btnReport5.UseVisualStyleBackColor = false;
            this.panelReport6.BackColor = System.Drawing.Color.FromArgb(68, 72, 71);
            this.panelReport6.Controls.Add(this.lblReport6);
            this.panelReport6.Controls.Add(this.btnReport6);
            this.panelReport6.Location = new System.Drawing.Point(320, 330);
            this.panelReport6.Name = "panelReport6";
            this.panelReport6.Size = new System.Drawing.Size(166, 210);
            this.panelReport6.TabIndex = 7;
            this.lblReport6.Font = new System.Drawing.Font("Montserrat Medium", 9F, System.Drawing.FontStyle.Bold);
            this.lblReport6.ForeColor = System.Drawing.Color.White;
            this.lblReport6.Location = new System.Drawing.Point(12, 14);
            this.lblReport6.Name = "lblReport6";
            this.lblReport6.Size = new System.Drawing.Size(142, 120);
            this.lblReport6.TabIndex = 0;
            this.lblReport6.Text = "Report 6\r\nDummy report data for section 6. Total records: 252. Status: Active.";
            this.btnReport6.BackColor = System.Drawing.Color.FromArgb(52, 193, 164);
            this.btnReport6.FlatAppearance.BorderSize = 0;
            this.btnReport6.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnReport6.Font = new System.Drawing.Font("Montserrat Medium", 9F, System.Drawing.FontStyle.Bold);
            this.btnReport6.ForeColor = System.Drawing.Color.White;
            this.btnReport6.Location = new System.Drawing.Point(12, 160);
            this.btnReport6.Name = "btnReport6";
            this.btnReport6.Size = new System.Drawing.Size(100, 32);
            this.btnReport6.TabIndex = 1;
            this.btnReport6.Text = "View";
            this.btnReport6.UseVisualStyleBackColor = false;
            this.panelReport7.BackColor = System.Drawing.Color.FromArgb(68, 72, 71);
            this.panelReport7.Controls.Add(this.lblReport7);
            this.panelReport7.Controls.Add(this.btnReport7);
            this.panelReport7.Location = new System.Drawing.Point(498, 330);
            this.panelReport7.Name = "panelReport7";
            this.panelReport7.Size = new System.Drawing.Size(166, 210);
            this.panelReport7.TabIndex = 8;
            this.lblReport7.Font = new System.Drawing.Font("Montserrat Medium", 9F, System.Drawing.FontStyle.Bold);
            this.lblReport7.ForeColor = System.Drawing.Color.White;
            this.lblReport7.Location = new System.Drawing.Point(12, 14);
            this.lblReport7.Name = "lblReport7";
            this.lblReport7.Size = new System.Drawing.Size(142, 120);
            this.lblReport7.TabIndex = 0;
            this.lblReport7.Text = "Report 7\r\nDummy report data for section 7. Total records: 294. Status: Active.";
            this.btnReport7.BackColor = System.Drawing.Color.FromArgb(52, 193, 164);
            this.btnReport7.FlatAppearance.BorderSize = 0;
            this.btnReport7.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnReport7.Font = new System.Drawing.Font("Montserrat Medium", 9F, System.Drawing.FontStyle.Bold);
            this.btnReport7.ForeColor = System.Drawing.Color.White;
            this.btnReport7.Location = new System.Drawing.Point(12, 160);
            this.btnReport7.Name = "btnReport7";
            this.btnReport7.Size = new System.Drawing.Size(100, 32);
            this.btnReport7.TabIndex = 1;
            this.btnReport7.Text = "View";
            this.btnReport7.UseVisualStyleBackColor = false;
            this.panelReport8.BackColor = System.Drawing.Color.FromArgb(68, 72, 71);
            this.panelReport8.Controls.Add(this.lblReport8);
            this.panelReport8.Controls.Add(this.btnReport8);
            this.panelReport8.Location = new System.Drawing.Point(676, 330);
            this.panelReport8.Name = "panelReport8";
            this.panelReport8.Size = new System.Drawing.Size(166, 210);
            this.panelReport8.TabIndex = 9;
            this.lblReport8.Font = new System.Drawing.Font("Montserrat Medium", 9F, System.Drawing.FontStyle.Bold);
            this.lblReport8.ForeColor = System.Drawing.Color.White;
            this.lblReport8.Location = new System.Drawing.Point(12, 14);
            this.lblReport8.Name = "lblReport8";
            this.lblReport8.Size = new System.Drawing.Size(142, 120);
            this.lblReport8.TabIndex = 0;
            this.lblReport8.Text = "Report 8\r\nDummy report data for section 8. Total records: 336. Status: Active.";
            this.btnReport8.BackColor = System.Drawing.Color.FromArgb(52, 193, 164);
            this.btnReport8.FlatAppearance.BorderSize = 0;
            this.btnReport8.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnReport8.Font = new System.Drawing.Font("Montserrat Medium", 9F, System.Drawing.FontStyle.Bold);
            this.btnReport8.ForeColor = System.Drawing.Color.White;
            this.btnReport8.Location = new System.Drawing.Point(12, 160);
            this.btnReport8.Name = "btnReport8";
            this.btnReport8.Size = new System.Drawing.Size(100, 32);
            this.btnReport8.TabIndex = 1;
            this.btnReport8.Text = "View";
            this.btnReport8.UseVisualStyleBackColor = false;
            this.panelReport9.BackColor = System.Drawing.Color.FromArgb(68, 72, 71);
            this.panelReport9.Controls.Add(this.lblReport9);
            this.panelReport9.Controls.Add(this.btnReport9);
            this.panelReport9.Location = new System.Drawing.Point(854, 330);
            this.panelReport9.Name = "panelReport9";
            this.panelReport9.Size = new System.Drawing.Size(166, 210);
            this.panelReport9.TabIndex = 10;
            this.lblReport9.Font = new System.Drawing.Font("Montserrat Medium", 9F, System.Drawing.FontStyle.Bold);
            this.lblReport9.ForeColor = System.Drawing.Color.White;
            this.lblReport9.Location = new System.Drawing.Point(12, 14);
            this.lblReport9.Name = "lblReport9";
            this.lblReport9.Size = new System.Drawing.Size(142, 120);
            this.lblReport9.TabIndex = 0;
            this.lblReport9.Text = "Report 9\r\nDummy report data for section 9. Total records: 378. Status: Active.";
            this.btnReport9.BackColor = System.Drawing.Color.FromArgb(52, 193, 164);
            this.btnReport9.FlatAppearance.BorderSize = 0;
            this.btnReport9.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnReport9.Font = new System.Drawing.Font("Montserrat Medium", 9F, System.Drawing.FontStyle.Bold);
            this.btnReport9.ForeColor = System.Drawing.Color.White;
            this.btnReport9.Location = new System.Drawing.Point(12, 160);
            this.btnReport9.Name = "btnReport9";
            this.btnReport9.Size = new System.Drawing.Size(100, 32);
            this.btnReport9.TabIndex = 1;
            this.btnReport9.Text = "View";
            this.btnReport9.UseVisualStyleBackColor = false;
            this.panelReport10.BackColor = System.Drawing.Color.FromArgb(68, 72, 71);
            this.panelReport10.Controls.Add(this.lblReport10);
            this.panelReport10.Controls.Add(this.btnReport10);
            this.panelReport10.Location = new System.Drawing.Point(1032, 330);
            this.panelReport10.Name = "panelReport10";
            this.panelReport10.Size = new System.Drawing.Size(166, 210);
            this.panelReport10.TabIndex = 11;
            this.lblReport10.Font = new System.Drawing.Font("Montserrat Medium", 9F, System.Drawing.FontStyle.Bold);
            this.lblReport10.ForeColor = System.Drawing.Color.White;
            this.lblReport10.Location = new System.Drawing.Point(12, 14);
            this.lblReport10.Name = "lblReport10";
            this.lblReport10.Size = new System.Drawing.Size(142, 120);
            this.lblReport10.TabIndex = 0;
            this.lblReport10.Text = "Report 10\r\nDummy report data for section 10. Total records: 420. Status: Active.";
            this.btnReport10.BackColor = System.Drawing.Color.FromArgb(52, 193, 164);
            this.btnReport10.FlatAppearance.BorderSize = 0;
            this.btnReport10.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnReport10.Font = new System.Drawing.Font("Montserrat Medium", 9F, System.Drawing.FontStyle.Bold);
            this.btnReport10.ForeColor = System.Drawing.Color.White;
            this.btnReport10.Location = new System.Drawing.Point(12, 160);
            this.btnReport10.Name = "btnReport10";
            this.btnReport10.Size = new System.Drawing.Size(100, 32);
            this.btnReport10.TabIndex = 1;
            this.btnReport10.Text = "View";
            this.btnReport10.UseVisualStyleBackColor = false;
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(44, 49, 49);
            this.ClientSize = new System.Drawing.Size(1180, 656);
            this.Controls.Add(this.panelSidebar);
            this.Controls.Add(this.lblPageTitle);
            this.Controls.Add(this.panelReport1);
            this.Controls.Add(this.panelReport2);
            this.Controls.Add(this.panelReport3);
            this.Controls.Add(this.panelReport4);
            this.Controls.Add(this.panelReport5);
            this.Controls.Add(this.panelReport6);
            this.Controls.Add(this.panelReport7);
            this.Controls.Add(this.panelReport8);
            this.Controls.Add(this.panelReport9);
            this.Controls.Add(this.panelReport10);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MaximizeBox = false;
            this.Name = "Admin_Reports";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Reports";
            this.panelSidebar.ResumeLayout(false);
            this.panelReport1.ResumeLayout(false);
            this.panelReport2.ResumeLayout(false);
            this.panelReport3.ResumeLayout(false);
            this.panelReport4.ResumeLayout(false);
            this.panelReport5.ResumeLayout(false);
            this.panelReport6.ResumeLayout(false);
            this.panelReport7.ResumeLayout(false);
            this.panelReport8.ResumeLayout(false);
            this.panelReport9.ResumeLayout(false);
            this.panelReport10.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        #endregion
        private System.Windows.Forms.Panel panelSidebar;
        private System.Windows.Forms.Label lblSideTitle;
        private System.Windows.Forms.Button btnExit;
        private System.Windows.Forms.Label lblPageTitle;
        private System.Windows.Forms.Panel panelReport1;
        private System.Windows.Forms.Label lblReport1;
        private System.Windows.Forms.Button btnReport1;
        private System.Windows.Forms.Panel panelReport2;
        private System.Windows.Forms.Label lblReport2;
        private System.Windows.Forms.Button btnReport2;
        private System.Windows.Forms.Panel panelReport3;
        private System.Windows.Forms.Label lblReport3;
        private System.Windows.Forms.Button btnReport3;
        private System.Windows.Forms.Panel panelReport4;
        private System.Windows.Forms.Label lblReport4;
        private System.Windows.Forms.Button btnReport4;
        private System.Windows.Forms.Panel panelReport5;
        private System.Windows.Forms.Label lblReport5;
        private System.Windows.Forms.Button btnReport5;
        private System.Windows.Forms.Panel panelReport6;
        private System.Windows.Forms.Label lblReport6;
        private System.Windows.Forms.Button btnReport6;
        private System.Windows.Forms.Panel panelReport7;
        private System.Windows.Forms.Label lblReport7;
        private System.Windows.Forms.Button btnReport7;
        private System.Windows.Forms.Panel panelReport8;
        private System.Windows.Forms.Label lblReport8;
        private System.Windows.Forms.Button btnReport8;
        private System.Windows.Forms.Panel panelReport9;
        private System.Windows.Forms.Label lblReport9;
        private System.Windows.Forms.Button btnReport9;
        private System.Windows.Forms.Panel panelReport10;
        private System.Windows.Forms.Label lblReport10;
        private System.Windows.Forms.Button btnReport10;
    }
}